### ISSUE TITLE
New akamai version

### ISSUE THREAD

**Issue by jaleli1341** [char/akamai-deobfuscator#10]
[Esurance](https://www.esurance.com/)  has an updated version of Akamai.
Sensor_data is now generated through ``bmak.get_telemetry()``, but I'm unable to deobfuscate the source code into something readable.
Any tips on how to deobfuscate this, or know of what obfuscation techniques they used that I can research about?

**Comment by voidstar0** [comment]
Is this the script? https://www.esurance.com/qlnA0X/jitUj/RHFJ-/Mg/3Eup8kLNN1OV/ag8GYDNC/Wzh2RQ/gRDVAB

If so, the obfuscation scheme seems to have changed drastically. I will look into updating to support this

**Comment by voidstar0** [comment]
After a quick glance, I was able to pretty easily reverse how the string encryption is performed.

It's just a simple XOR cipher as shown below:
```js
function decrypt(encryptedStr, offset) {
    var key = 'bj4[sd[wdsJMmJN+xK=t+wR]7\"DcID';
    var decryptedStr = '';

    for (var currentChar = 0; currentChar < encryptedStr.length; ++currentChar) {
        var keyIndex = (currentChar + offset) % key.length;
        var plaintextCharCode = encryptedStr.charCodeAt(currentChar) ^ key.charCodeAt(keyIndex);
        decryptedStr += charCodeToStr(plaintextCharCode);
    }
    return decryptedStr;
}

function charCodeToStr(char) {
    if (char < 65535) {
        return String.fromCharCode(char);
    } else {
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCodePoint
        char -= 65536;
        return String.fromCharCode(0xD800 + (char >> 10), 0xDC00 + (char % 0x400))
    }
}
// decrypt("A,\u0002;\u0005\u0016", 925) -> charAt


```

Additionally, they've added some new obfuscation techniques such as control flow flattening. Luckily for us, this is not something I haven't seen before and I already have an idea of how to tackle it.

Will be updating soon.

**Comment by jaleli1341** [comment]
You never cease to amaze me. I was reading through obfuscation techniques and couldn't find an answer to it.
I'll try to deobfuscate it myself as well for learning purposes. Thank you for the pointer about the XOR cipher

**Comment by cbxhpy** [comment]
> 

are you solve it??   i used your code ,but can not decrpy source code .

**Comment by voidstar0** [comment]
Apologies, this project is now in an archived state and will not be receiving updates.

This started as a fun learning and teaching project but I feel it likely only benefits those with malicious intent (credential stuffers) and those looking to make a profit from open source projects without giving back.

I have the code for deobfuscating current Akamai but I will not be releasing it for the reasons listed above. If you do wish to learn from it then message me on Discord (`veritas#0001`) and I may be able to provide the source to you depending on how I am feeling.
