### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by amzse826** [char/akamai-deobfuscator#2]
I am unable to use this as I receive the error connect ECONNREFUSED 127.0.0.1:80 when trying a site with akamai.

**Comment by jimtje** [comment]
Pretty sure you aren't running the validation end of Akamai's bot management api on your localhost at port 80. The code takes a lot of dynamic variables to route what data goes where and merely deobfuscating the script isn't likely to be sufficient without engineering the underlying mechanism to operate is a more realistic way, with enough variance.

**Comment by godpowerscn** [comment]
how can i "running the validation end of Akamai's bot management api on your localhost at port 80"?

**Comment by jimtje** [comment]
You can't, but it was what the error message indicated OP was trying to do. You need a real endpoint to validate the payload.
