### ISSUE TITLE
'Undeobfuscatable' script

### ISSUE THREAD

**Issue by lipowskm** [char/akamai-deobfuscator#5]
Hello,
Any chance on this one?
https://www.zalando-lounge.pl/akam/11/193215fc

This also Akamai script, but probably not from Bot Manager. Unfortunately deobfuscator can't handle this one.

**Comment by lipowskm** [comment]
I've noticed that the endpoint is being changed dynamically, so here's a copy of the script:
https://pastebin.com/j4N5Chf1

**Comment by voidstar0** [comment]
Thanks! Fixed in latest commit
